### ISSUE TITLE
Experimentally determined or computationally predicted

### ISSUE THREAD

**Issue by sumenties** [theochem/B3DB#28]
Hi, I would like to know whether the molecules with categorical labels are experimentally determined or computationally predicted. Thank you

**Comment by PaulWAyers** [comment]
@sumenties as [explained in the paper](https://www.nature.com/articles/s41597-021-01069-5), the data in B3DB is extracted from various (experimental) research papers and surveys of the associated literature. 

@FanwangM I will update the GitHub readme to make this a little bit more clear.

**Comment by FanwangM** [comment]
I was about to update the README.md file, but noticed that you have made improvements already. Thank you. @PaulWAyers

**Comment by sumenties** [comment]
@PaulWAyers thank you for the response. I have been told by my professor to only use wet-lab-validated BBB molecules. Sorry, I was a little concerned because this is my master's dissertation project.
