### ISSUE TITLE
What is the smiles_result column?

### ISSUE THREAD

**Issue by HenryJia** [theochem/B3DB#29]
Hi,

I've noticed that there's a smiles_result column in the regression dataset, which is not present in the classification dataset.

What exactly is this, is this the cleaned up SMILES or something else? If it is, why is it not present in the classification dataset?

Thanks

**Comment by PaulWAyers** [comment]
@FanwangM we should probably document our datasets better.

**Comment by FanwangM** [comment]
Thank you for your interest in our data.

The `smiles_result` column denotes the result of parsing the isomeric SMILES with PubChem CID using the original SMILES strings as input. This is driven by the belief that stereochemistry is important for BBB permeability. Therefore, we should stick to this column for further studies. But I will rename `smiles_result` to `SMILES` to avoid confusion in the coming PR. @HenryJia

**Comment by FanwangM** [comment]
I am going to close this issue but feel free to reopen it if you still have problems with it.
